server {
    listen 80;

    # Routs for frontend
    location / {
        proxy_pass http://frontend:3000;
    }

    # REST API backend
    location /api/ {
        proxy_pass http://backend:8000/;
    }

    # WebSockets for chat/RAG statuses
    location /ws/ {
        proxy_pass http://backend:8000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}