from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlmodel import select
from fastapi.security import OAuth2PasswordRequestForm # to make the "Authorize" button work
from typing import Annotated

# import our files
from database import get_db
from models import User, UserCreate, Token # no longer need the UserLogin Pydantic model
from auth_utils import get_password_hash, verify_password, create_access_token

router = APIRouter(prefix="/auth", tags=["Authentication"])

signup_responses = {
	status.HTTP_201_CREATED: {
		"description": "User created successfully",
		"content": {
			"application/json": {
				"example": {"message": "User created successfully", "user_id": 1}
			}
		},
	},
	status.HTTP_409_CONFLICT: {
		"description": "Conflict: Email or Nickname already exists",
		"content": {
			"application/json": {
				"examples": {
					"email_exists": {
						"summary": "Email already registered",
						"value": {"detail": "E-Mail already registered."},
					},
					"nickname_exists": {
						"summary": "Nickname already in use",
						"value": {"detail": "Nickname already in use."},
					},
				}
			}
		},
	},
}

@router.post(
	"/signup", 
	status_code=status.HTTP_201_CREATED,
	responses=signup_responses
)
# get_session from database.py opens a communication pipeline with the db
async def signup(user_data: UserCreate, session: Session = Depends(get_db)):
	"""Handles new user registration."""

	# Check for unique email and nickname
	query = select(User).where(
		(User.email == user_data.email) | (User.nickname == user_data.nickname)
	)
	 # sends query to database and deblocks
	result = session.execute(query)
	existing_user = result.first()

	if existing_user:
		if existing_user.email == user_data.email:
			raise HTTPException(
				status_code=status.HTTP_409_CONFLICT,
				detail="E-Mail already registered."
			)
		if existing_user.nickname == user_data.nickname:
			raise HTTPException(
				status_code=status.HTTP_409_CONFLICT,
				detail="Nickname already in use."
			)
	# Create a new User instance
	new_user = User(
		email=user_data.email,
		nickname=user_data.nickname,
		hashed_password=get_password_hash(user_data.password)
	)

	# Adding to a session. Staging step.
	session.add(new_user)
	# Commit (Save). SQLAlchemy converts Python data into an SQL command: 
 	# INSERT INTO users (email, nickname, ...) VALUES (...).
 	# It then sends this SQL command over the network to PostgreSQL.
	session.commit()
	# Retrieve the ID generated by Postgres
	session.refresh(new_user)
	return {"message": "User created successfully", "user_id": new_user.id}

@router.post(
	"/login",
	response_model=Token,
	responses={
		401: {
			"description": "Unauthorized",
			"content": {
				"application/json": {
					"example": {"detail": "Invalid email or password"}
				}
			}
		}
	}
	)
async def login(
	form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
	session: Session = Depends(get_db)
):
	"""Handles user login and issues a JWT"""
	# form_data has 'username' and 'password' fields
	query = select(User).where(User.email == form_data.username)
	result = session.execute(query)
	user = result.scalars().first()

	if not user or not verify_password(form_data.password, user.hashed_password):
		raise HTTPException(
			status_code=status.HTTP_401_UNAUTHORIZED,
			detail="Invalid email or password",
			headers={"WWW-Authenticate": "Bearer"}
		)
	
	access_token = create_access_token(
		data={"sub": user.email, "nickname": user.nickname})

	return {"access_token": access_token, "token_type": "bearer"}
