# to run:
# uvicorn main:app --reload

from contextlib import asynccontextmanager
from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
import os

# import our files
import models, schemas
from database import SessionLocal, engine, Base

# from sqlmodel import SQLModel, create_engine
# engine = create_engine(DATABASE_URL)
#
#    This line looks at all classes with (table=True) and creates them in Postgres
#    SQLModel.metadata.create_all(engine)

@asynccontextmanager
async def lifespan(app: FastAPI):
	# Code here runs on startup
	print("Startup: Creating database tables...")
	# Create tables in the database
	# SQLAlchemy will check if the tables exist and create them if not
	models.Base.metadata.create_all(bind=engine)
	yield
	# Code here runs on shutdown
	print("Shutdown: Application closing.")

app = FastAPI(lifespan=lifespan)

# Function to get database session
def get_db():
	db = SessionLocal()
	try:
		yield db
	finally:
		db.close()

@app.get("/")
def read_root():
	return {"message": "Hello from Python 3.12 and WSL2!"}

# response_model=schemas.SignupMessage: This is very important! 
# By using the Pydantic schema in the response, you ensure that 
# FastAPI will not send the password back to the client, even if 
# it is in the models.User object.
@app.post("/signup", response_model=schemas.SignupMessage)
def signup(user_data: schemas.UserCreate, db: Session = Depends(get_db)):

	# Check if email is busy
	db_user = db.query(models.User).filter(models.User.email == user_data.email).first()
	if db_user:
		raise HTTPException(status_code=409, detail="Email already registered")

	# Check if nickname is busy
	db_nickname = db.query(models.User).filter(models.User.nickname == user_data.nickname).first()
	if db_nickname:
		raise HTTPException(status_code=409, detail="Nickname already taken")

	# Creating a model object
	new_user = models.User(
		email=user_data.email,
		nickname=user_data.nickname,
		hashed_password=user_data.password + "not_safe_hash" # we need to use passlib!
	)
	# Adding to a session
	# Staging step. SQLAlchemy tracks it
	db.add(new_user)
	# Commit (Save). SQLAlchemy performs a Flush
	# SQLAlchemy converts Python data into an SQL command: 
	# INSERT INTO users (email, nickname, ...) VALUES (...).
	# It then sends this SQL command over the network to PostgreSQL.
	db.commit()
	# Retrieve the ID generated by Postgres
	db.refresh(new_user)
	return {"message": "User created successfully", "user_id": new_user.id}
